<?php

declare(strict_types=1);

namespace App\Installer;

use App\Paths;

final class ConfigWriter
{
    /**
     * Runtime settings live in the `app_settings` database table. This file only stores PDO bootstrap.
     *
     * @param array{pdo: array<string, mixed>, data_dir?: string} $config
     */
    public static function writeBootstrap(array $config): void
    {
        if (!isset($config['pdo']) || !is_array($config['pdo'])) {
            throw new \RuntimeException('Bootstrap config must contain a pdo array.');
        }

        $dataDir = isset($config['data_dir']) && is_string($config['data_dir']) && trim($config['data_dir']) !== ''
            ? trim($config['data_dir'])
            : './wgw-content';
        $pdo = $config['pdo'];

        $php = <<<'PHP'
<?php

declare(strict_types=1);

/**
 * Local bootstrap config (WordPress-style constants).
 *
 * Generated by installer. Everything else—timezone, base_uri, auth_realm, feature toggles, admin users—
 * lives in the app_settings table (/admin -> Settings).
 */

PHP;

        $php .= "\n";
        $php .= "// Optional instance data directory (default: ./wgw-content).\n";
        $php .= "// Supports relative (./wgw-content, ../shared/wgw-content) and absolute paths.\n";
        $php .= "// SABRE_DATA_DIR still overrides this value when set.\n";
        $php .= "defined('WGW_DATA_DIR') || define('WGW_DATA_DIR', ".var_export($dataDir, true).");\n\n";
        $php .= "// Release feed used by /admin/updates \"Check now\".\n";
        $php .= "// Can point to manifest.json directly or GitHub releases/latest API URL.\n";
        $php .= "defined('WGW_UPDATE_FEED_URL') || define('WGW_UPDATE_FEED_URL', 'https://github.com/woutervroege/wegotworkspace/releases/latest/download/manifest.json');\n\n";

        if (isset($pdo['sqlite_file']) && is_string($pdo['sqlite_file']) && trim($pdo['sqlite_file']) !== '') {
            $sqliteFile = trim($pdo['sqlite_file']);
            $php .= "// SQLite (recommended): path relative to runtime root or absolute path.\n";
            $php .= "// If omitted, runtime uses WGW_DATA_DIR + '/db.sqlite'.\n";
            $php .= "defined('WGW_DB_SQLITE_FILE') || define('WGW_DB_SQLITE_FILE', ".var_export($sqliteFile, true).");\n\n";
            $php .= "// MySQL / MariaDB: comment out WGW_DB_SQLITE_FILE above and uncomment below.\n";
            $php .= "// define('WGW_DB_DSN', 'mysql:host=127.0.0.1;port=3306;dbname=wegotworkspace;charset=utf8mb4');\n";
            $php .= "// define('WGW_DB_USER', 'db_user');\n";
            $php .= "// define('WGW_DB_PASSWORD', 'db_password');\n";
        } elseif (isset($pdo['dsn']) && is_string($pdo['dsn']) && trim($pdo['dsn']) !== '') {
            $dsn = trim($pdo['dsn']);
            if (str_starts_with($dsn, 'sqlite:')) {
                $sqliteFile = substr($dsn, 7);
                if ($sqliteFile === '') {
                    throw new \RuntimeException('Invalid sqlite dsn in bootstrap config.');
                }
                $php .= "// SQLite (recommended): path relative to runtime root or absolute path.\n";
                $php .= "// If omitted, runtime uses WGW_DATA_DIR + '/db.sqlite'.\n";
                $php .= "defined('WGW_DB_SQLITE_FILE') || define('WGW_DB_SQLITE_FILE', ".var_export($sqliteFile, true).");\n\n";
                $php .= "// MySQL / MariaDB: comment out WGW_DB_SQLITE_FILE above and uncomment below.\n";
                $php .= "// define('WGW_DB_DSN', 'mysql:host=127.0.0.1;port=3306;dbname=wegotworkspace;charset=utf8mb4');\n";
                $php .= "// define('WGW_DB_USER', 'db_user');\n";
                $php .= "// define('WGW_DB_PASSWORD', 'db_password');\n";
            } else {
                $user = isset($pdo['user']) && is_string($pdo['user']) ? $pdo['user'] : '';
                $password = isset($pdo['password']) && is_string($pdo['password']) ? $pdo['password'] : '';
                $php .= "// SQLite (recommended): optional path relative to runtime root or absolute path.\n";
                $php .= "// If omitted, runtime uses WGW_DATA_DIR + '/db.sqlite'.\n";
                $php .= "// defined('WGW_DB_SQLITE_FILE') || define('WGW_DB_SQLITE_FILE', './wgw-content/db.sqlite');\n\n";
                $php .= "// MySQL / MariaDB\n";
                $php .= "defined('WGW_DB_DSN') || define('WGW_DB_DSN', ".var_export($dsn, true).");\n";
                $php .= "defined('WGW_DB_USER') || define('WGW_DB_USER', ".var_export($user, true).");\n";
                $php .= "defined('WGW_DB_PASSWORD') || define('WGW_DB_PASSWORD', ".var_export($password, true).");\n";
            }
        } else {
            throw new \RuntimeException('Invalid bootstrap pdo config; expected sqlite_file or dsn.');
        }

        self::writeToPath(self::primaryConfigPath(), $php);
    }

    /**
     * @param array<string, mixed> $config
     */
    public static function write(array $config): void
    {
        self::writeRaw($config, '');
    }

    /**
     * @param array<string, mixed> $config
     */
    private static function writeRaw(array $config, string $docComment): void
    {
        $path = Paths::localConfig();
        $export = var_export($config, true);
        $header = "<?php\n\ndeclare(strict_types=1);\n\n";
        if ($docComment !== '') {
            $header .= $docComment;
        }
        $php = $header.'return '.$export.";\n";
        self::writeToPath($path, $php);
    }

    private static function primaryConfigPath(): string
    {
        return Paths::configDir().'/wgw-config.php';
    }

    private static function writeToPath(string $path, string $php): void
    {
        $dir = dirname($path);
        if (!is_dir($dir)) {
            @mkdir($dir, 0775, true);
        }
        if (file_put_contents($path, $php, LOCK_EX) === false) {
            throw new \RuntimeException('Could not write wgw-config.php');
        }
        @chmod($path, 0640);
    }
}
