export const chatUiLabels = {
  empty: "No messages yet",
  deleted: "This message was deleted",
  edited: "Edited",
  reply: "Reply",
  react: "Add reaction",
  edit: "Edit",
  delete: "Delete",
  send: "Send",
  cancel: "Cancel",
  mentionList: "Mention someone",
  mentionEmpty: "No matches",
  previewMissing: "Preview unavailable",
  previewExternal: "External link",
  composerPlaceholder: "Write a message…",
  sendHint: "Return to send · Shift + Return for new line",
  today: "Today",
  yesterday: "Yesterday",
} as const;
