import { driveLabels } from "@/drive-core/src/drive-labels";
import { filesBrowserSidebarLabels } from "@/drive-core/src/files-browser-sidebar";

export const docsLabels = {
  toastSaved: "Document saved",
  toastSynced: "Changes synced",
  emptyTitle: "No document open",
  emptyDescription: "Open a Markdown file from Drive to start editing.",
  homeTitle: "Documents",
  homeSearchPlaceholder: "Search documents...",
  homeEmpty: "No documents yet. Create or upload a Markdown file in Drive.",
  homeSharedEmpty: "No shared documents yet.",
  homeRecentEmpty: "No recent documents yet.",
  homeStarredEmpty: "No starred documents yet.",
  homeTrashEmpty: "Trash is empty.",
  homeLoading: "Loading documents…",
  homeLoadMore: "Load more",
  homeLoadError: "Could not load documents.",
  homeNotAvailableOffline: "This document is not available offline.",
  /** Drive SST — single source (`driveLabels`). */
  offlineAvailable: driveLabels.offlineAvailable,
  syncingOffline: "Syncing offline",
  offlinePendingSync: driveLabels.offlinePendingSync,
  syncFailedTitle: "Some changes could not sync",
  syncFailedMessage: "Your edits are saved locally. Retry when you are back online.",
  retrySync: "Retry sync",
  conflictTitle: "Document conflict",
  conflictDescription: (title: string) =>
    `"${title}" changed on the server while you were offline. Keep your version or use the server copy?`,
  conflictKeepMine: "Keep mine",
  conflictUseServer: "Use server",
  homeLocationColumn: "Location",
  homeNewDocument: driveLabels.newMarkdown,
  homeCreateError: "Could not create a new document.",
  /** Primary home — SST with Drive (`filesBrowserSidebarLabels`; Drive uses "My Files"). */
  homeAllDocs: filesBrowserSidebarLabels.homeDocs,
  homeSharedWithMe: driveLabels.sidebarSharedWithMe,
  homeRecent: driveLabels.sidebarRecent,
  homeStarred: driveLabels.sidebarStarred,
  homeTrash: driveLabels.sidebarTrash,
  /** Location column for docs shared with the current user. */
  homeSharedBy: driveLabels.sharedBy,
  homeDrivesSection: filesBrowserSidebarLabels.drivesSection,
  /** Personal-drive display label (SST). Drive UI path key remains `"My Drive"`. */
  homeMyDrive: filesBrowserSidebarLabels.personalDrive,
  /** Docs home confirm copy (Drive hardcodes a slightly different permanent-delete body). */
  homeDeletePermanentlyTitle: "Delete permanently?",
  homeDeletePermanentlyOne: "This will permanently delete 1 file.",
  homeDeletePermanentlyMany: (count: number) => `This will permanently delete ${count} files.`,
  homeDeletePermanentlyAction: "Delete",
  homeMoveToTrashTitle: "Move to Trash?",
  homeMoveToTrashOne: "This will move 1 file to Trash.",
  homeMoveToTrashMany: (count: number) => `This will move ${count} files to Trash.`,
  homeMoveToTrashAction: "Move to Trash",
  loadError: "Could not load this document.",
  saveError: "Could not save this document.",
  renameError: "Could not rename this document.",
  print: "Print",
  share: driveLabels.detailShare,
  viewSource: "Edit source",
  hideSource: "Hide source",
  rename: driveLabels.detailRename,
  /** Docs rename dialog copy (Drive uses generic "Rename item"). */
  renameDialogTitle: "Rename document",
  renameDialogDescription: "Change the name; the file extension cannot be edited.",
  renameAction: driveLabels.renameAction,
  cancel: driveLabels.cancel,
  pendingSync: "Unsaved changes",
  pendingSyncFailed: "Save failed — changes not on server",
  sidebarOutline: "Outline",
  sidebarBackToHome: "Back to docs home",
  outlineEmpty: "No headings in this document yet.",
  statsWords: (count: number) => `${count.toLocaleString()} words`,
  statsCharacters: (count: number) => `${count.toLocaleString()} characters`,
  /** Clarification for the detail-footer last-edited chip (tooltip + aria-label; chip shows time only). */
  editedLabel: "Last edited",
  reviewSidebarTitle: "Review",
  reviewCloseSidebar: "Close review panel",
  reviewEmpty:
    "No comments or suggestions yet. Select text to comment, or switch to Suggest mode to track edits.",
  reviewEmptyResolved: "No resolved comments yet.",
  reviewCountOne: "1 item",
  reviewCountMany: (count: number) => `${count} items`,
  reviewToggleShow: "Show review",
  reviewToggleHide: "Hide review",
  /** Suggest-mode header toggle (Tasks “Show completed” state-button pattern). */
  editMode: "Edit",
  suggestMode: "Suggest",
  editingModeAria: "Editing mode",
  toastSwitchedToEditMode: "Switched to Edit mode",
  toastSwitchedToSuggestMode: "Switched to Suggest mode",
  reviewFilterAria: "Review status",
  reviewTabOpen: "Open",
  reviewTabResolved: "Resolved",
  commentsSidebarTitle: "Comments",
  commentsCloseSidebar: "Close comments",
  commentsFilterLabel: "Comment status",
  commentsFilterOpen: "Open",
  commentsFilterResolved: "Resolved",
  commentsEmpty: "No comments yet. Select text and click Comment in the toolbar.",
  commentsAddFromSelection: "Comment",
  commentsAddFromSelectionDisabledNoSelection: "Select text to comment",
  commentsAddFromSelectionDisabledViewSource: "Comments are disabled in source view",
  commentsAddFromSelectionDisabledReadOnly: "View-only access cannot add comments",
  commentsCountOne: "1 open",
  commentsCountMany: (count: number) => `${count} open`,
  commentsComposePlaceholder: "Add a comment…",
  commentsAdd: "Comment",
  commentsToggleShow: "Show comments",
  commentsToggleHide: "Hide comments",
  commentsReplyPlaceholder: "Reply…",
  commentsReplyAction: "Post",
  commentsResolve: "Resolve thread",
  commentsDelete: "Delete thread",
  suggestionsSidebarTitle: "Suggestions",
  suggestionsCloseSidebar: "Close suggestions",
  suggestionsEmpty: "No suggestions yet. Switch to Suggest mode and edit the document.",
  suggestionsCountOne: "1 pending",
  suggestionsCountMany: (count: number) => `${count} pending`,
  suggestionsToggleShow: "Show suggestions",
  suggestionsToggleHide: "Hide suggestions",
  suggestionsAccept: "Accept suggestion",
  suggestionsReject: "Reject suggestion",
} as const;

export type DocsUILabels = typeof docsLabels;

export function mergeDocsLabels(overrides?: Partial<DocsUILabels>): DocsUILabels {
  return { ...docsLabels, ...overrides };
}
