export const docsLabels = {
  toastSaved: "Document saved",
  toastSynced: "Changes synced",
  emptyTitle: "No document open",
  emptyDescription: "Open a Markdown file from Drive to start editing.",
  homeTitle: "Documents",
  homeSearchPlaceholder: "Search documents...",
  homeEmpty: "No documents yet. Create or upload a Markdown file in Drive.",
  homeLoading: "Loading documents…",
  homeLoadMore: "Load more",
  homeLoadError: "Could not load documents.",
  homeNotAvailableOffline: "This document is not available offline.",
  offlineAvailable: "Available offline",
  offlinePendingSync: "Pending sync",
  syncFailedTitle: "Some changes could not sync",
  syncFailedMessage: "Your edits are saved locally. Retry when you are back online.",
  retrySync: "Retry sync",
  conflictTitle: "Document conflict",
  conflictDescription: (title: string) =>
    `"${title}" changed on the server while you were offline. Keep your version or use the server copy?`,
  conflictKeepMine: "Keep mine",
  conflictUseServer: "Use server",
  homeLocationColumn: "Location",
  homeNewDocument: "New document",
  homeCreateError: "Could not create a new document.",
  homeAllDocs: "All docs",
  homeDrivesSection: "Drives",
  homeMyDrive: "My Drive",
  loadError: "Could not load this document.",
  saveError: "Could not save this document.",
  renameError: "Could not rename this document.",
  print: "Print",
  viewSource: "Edit source",
  hideSource: "Hide source",
  rename: "Rename",
  renameDialogTitle: "Rename document",
  renameDialogDescription: "Change the name; the file extension cannot be edited.",
  renameAction: "Rename",
  cancel: "Cancel",
  pendingSync: "Unsaved changes",
  pendingSyncFailed: "Save failed — changes not on server",
  sidebarOutline: "Outline",
  sidebarBackToHome: "Back to docs home",
  outlineEmpty: "No headings in this document yet.",
  statsWords: (count: number) => `${count.toLocaleString()} words`,
  statsCharacters: (count: number) => `${count.toLocaleString()} characters`,
  reviewSidebarTitle: "Review",
  reviewCloseSidebar: "Close review panel",
  reviewEmpty:
    "No comments or suggestions yet. Select text to comment, or switch to Suggest mode to track edits.",
  reviewCountOne: "1 item",
  reviewCountMany: (count: number) => `${count} items`,
  reviewToggleShow: "Show review",
  reviewToggleHide: "Hide review",
  commentsSidebarTitle: "Comments",
  commentsCloseSidebar: "Close comments",
  commentsFilterLabel: "Comment status",
  commentsFilterOpen: "Open",
  commentsFilterResolved: "Resolved",
  commentsEmpty: "No comments yet. Select text and click Comment in the toolbar.",
  commentsAddFromSelection: "Comment",
  commentsAddFromSelectionDisabledNoSelection: "Select text to comment",
  commentsAddFromSelectionDisabledViewSource: "Comments are disabled in source view",
  commentsCountOne: "1 open",
  commentsCountMany: (count: number) => `${count} open`,
  commentsComposePlaceholder: "Add a comment…",
  commentsAdd: "Comment",
  commentsToggleShow: "Show comments",
  commentsToggleHide: "Hide comments",
  commentsReplyPlaceholder: "Reply…",
  commentsReplyAction: "Post",
  commentsResolve: "Resolve thread",
  commentsDelete: "Delete thread",
  suggestionsSidebarTitle: "Suggestions",
  suggestionsCloseSidebar: "Close suggestions",
  suggestionsEmpty: "No suggestions yet. Switch to Suggest mode and edit the document.",
  suggestionsCountOne: "1 pending",
  suggestionsCountMany: (count: number) => `${count} pending`,
  suggestionsToggleShow: "Show suggestions",
  suggestionsToggleHide: "Hide suggestions",
  suggestionsAccept: "Accept suggestion",
  suggestionsReject: "Reject suggestion",
  pageSizeLabel: "Page size",
} as const;

export type DocsUILabels = typeof docsLabels;

export function mergeDocsLabels(overrides?: Partial<DocsUILabels>): DocsUILabels {
  return { ...docsLabels, ...overrides };
}
