export const meetLabels = {
  productName: "Meet",
  callEndedTitle: "Call ended",
  missingInviteTitle: "Nothing here",
  missingInviteBody: "This meeting is not active. Ask the host for a fresh invite link.",
  checkingInviteTitle: "Checking meeting",
  checkingInviteBody: "Validating this invite link...",
  waitingForHostTitle: "Waiting for the host",
  waitingForHostBody: "This meeting has not started yet. You can join when the host arrives.",
  inviteErrorTitle: "Could not check this meeting",
  inviteErrorBody: "Something went wrong while checking this invite. Try again.",
  lobbyJoinTitle: "Ready to join?",
  lobbyHostTitle: "Ready when you are.",
  displayNameLabel: "Display name",
  cameraLabel: "Camera",
  microphoneLabel: "Microphone",
  speakerLabel: "Speaker",
  joinMeeting: "Join meeting",
  askToJoin: "Ask to join",
  startMeeting: "Start meeting",
  inviteRequired: "Invite link required",
  cancelRequest: "Cancel request",
  knocking: "Knocking",
  knockingHint: "Waiting for the host to let you in",
  leaveCall: "Leave call",
  endCall: "End call",
  leaveCallTitle: "Leave this call?",
  endCallTitle: "End call for everyone?",
  leaveCallDescription: "This only disconnects you from the meeting.",
  endCallDescription: "This will disconnect all participants from the meeting.",
  shareLinkHint: "Anyone with this link can join the room.",
  shareLinkPlaceholder: "Start a meeting to generate a share link",
  shareLinkWaiting: "Share link will appear here.",
  copyLink: "Copy link",
  linkCopied: "Link copied",
  chatTitle: "Chat",
  chatEmpty: "Messages from participants will appear here.",
  chatPlaceholder: "Send a message",
  sendMessage: "Send",
  waitingForOthers: "Waiting for others to join...",
  presenting: "Presenting",
  sharingScreen: "You're sharing your screen",
  participantsTooltip: (count: number) => `${count} of 4 participants`,
  toggleChatShow: "Show chat",
  toggleChatHide: "Hide chat",
  shareScreen: "Share screen",
  stopSharing: "Stop sharing",
  devices: "Devices",
  shareLink: "Share link",
  signOut: "Sign out",
  someoneKnocking: "Someone is knocking to join.",
  wantsToJoin: "wants to join",
  waitingToJoin: (count: number) => `${count} waiting to join`,
  muteParticipant: "Mute participant",
  muteSoon: (name: string) => `Mute controls for ${name} will be added soon`,
  pipNotReady: "Camera preview is not ready yet.",
  pipUnsupported: "Picture-in-Picture is not supported in this browser.",
  pipError: "Could not open Picture-in-Picture.",
  openPip: "Open picture-in-picture",
  openSystemPip: "Open system Picture-in-Picture",
  youLabel: "You",
  selfPreview: (name: string) => `${name} (you)`,
  participantJoined: (name: string) => `${name} joined the call`,
  participantLeft: (name: string) => `${name} left the call`,
  sidebarChannels: "My channels",
  sidebarSharedWithMe: "Shared with me",
  sidebarDirectMessages: "Direct messages",
  sidebarMeetings: "Meetings",
  dmComposer: (name: string) => `Message ${name}`,
  newChannel: "New channel",
  newMeeting: "New meeting",
  newChannelMenu: "New",
  editChannel: "Edit channel",
  editMeeting: "Edit meeting",
  channelNameLabel: "Name",
  channelKindLabel: "Type",
  channelKindChannel: "Channel",
  channelKindMeeting: "Meeting room",
  channelScopeLabel: "Owner",
  channelScopePersonal: (ownerLabel: string) => ownerLabel,
  channelScopeGroup: (name: string) => name,
  channelScopeReadOnlyLabel: "Owner",
  changeChannelOwnerConfirmTitle: "Change owner?",
  changeChannelOwnerConfirmToGroup: (groupName: string) =>
    `Move this collection to ${groupName}? People in that group will see it.`,
  changeChannelOwnerConfirmToPersonal: "Move this collection back to your personal space?",
  changeChannelOwnerConfirm: "Change owner",
  createChannelButton: "Create",
  saveChannelButton: "Save",
  cancel: "Cancel",
  shareChannelSectionTitle: "People with access",
  shareChannelSectionHint: "Share this channel with a person or group.",
  shareChannelAddPlaceholder: "Add people or groups",
  shareChannelSearchEmpty: "No matching people or groups.",
  shareChannelOffline: "Sharing needs a connection.",
  removeChannelShareTitle: "Remove access?",
  removeChannelShareConfirm: "Remove",
  guestLinkHint: "Anyone with this link can join as a guest.",
  guestLinkAfterCreate: "A guest link will be ready after you create this meeting room.",
  emptyChannelMain: "Select a channel to start chatting.",
  chatColumnPlaceholder: "Chat will appear here.",
  membersCount: (count: number) => `${count} members`,
  startCall: "Start call",
  joinCall: "Join call",
  leaveCallStub: "Stop preview call",
  expandCall: "Expand call",
  collapseCall: "Hide call",
  restoreCall: "Show chat",
  resizeCall: "Resize call stage",
  threadTitle: "Thread",
  threadClose: "Close thread",
} as const;
