export const meetLabels = {
  productName: "Meet",
  callEndedTitle: "Call ended",
  missingInviteTitle: "Nothing here",
  missingInviteBody: "This meeting is not active. Ask the host for a fresh invite link.",
  checkingInviteTitle: "Checking meeting",
  checkingInviteBody: "Validating this invite link...",
  waitingForHostTitle: "Waiting for the host",
  waitingForHostBody: "This meeting has not started yet. You can join when the host arrives.",
  inviteErrorTitle: "Could not check this meeting",
  inviteErrorBody: "Something went wrong while checking this invite. Try again.",
  lobbyJoinTitle: "Ready to join?",
  lobbyHostTitle: "Ready when you are.",
  invitedTitle: "You're invited to a meet",
  guestLobbyRegion: "Meeting lobby",
  guestLobbyMediaRegion: "Camera preview and devices",
  yourNameLabel: "Your name",
  displayNameLabel: "Display name",
  cameraLabel: "Camera",
  microphoneLabel: "Microphone",
  speakerLabel: "Speaker",
  cameraOff: "Camera is off",
  speakToTest: "Speak to test",
  joinMeeting: "Join meeting",
  askToJoin: "Ask to join",
  knockToJoin: "Knock to join",
  startMeeting: "Start meeting",
  inviteRequired: "Invite link required",
  cancelRequest: "Cancel request",
  cancelKnock: "Cancel knock",
  knocking: "Knocking",
  knockingHint: "Waiting for the host to let you in",
  knockNoAccount: "No account needed. The host will let you in.",
  leaveCall: "Leave call",
  endCall: "End call",
  leaveCallTitle: "Leave this call?",
  endCallTitle: "End call for everyone?",
  leaveCallDescription: "This only disconnects you from the meeting.",
  endCallDescription: "This will disconnect all participants from the meeting.",
  shareLinkHint: "Anyone with this link can join the room.",
  shareLinkPlaceholder: "Start a meeting to generate a share link",
  shareLinkWaiting: "Share link will appear here.",
  copyLink: "Copy link",
  meetingLinkLabel: "Meeting link",
  linkCopied: "Link copied",
  chatTitle: "Chat",
  chatClose: "Close chat",
  chatEmpty: "Messages from participants will appear here.",
  chatPlaceholder: "Send a message",
  sendMessage: "Send",
  waitingForOthers: "Waiting for others to join...",
  presenting: "Presenting",
  sharingScreen: "You're sharing your screen",
  participantsTooltip: (count: number) => `${count} of 4 participants`,
  toggleChatShow: "Show chat",
  toggleChatHide: "Hide chat",
  shareScreen: "Share screen",
  stopSharing: "Stop sharing",
  shareScreenUnsupported: "Screen sharing isn't available in this browser.",
  shareScreenFailed: "Could not share your screen.",
  devices: "Devices",
  shareLink: "Share link",
  signOut: "Sign out",
  someoneKnocking: "Someone is knocking to join.",
  wantsToJoin: "wants to join",
  waitingToJoin: (count: number) => `${count} waiting to join`,
  admit: "Admit",
  deny: "Deny",
  admitName: (name: string) => `Admit ${name}`,
  denyName: (name: string) => `Deny ${name}`,
  knockWaitTitle: (channel: string) => `Asking to join ${channel}`,
  knockWaitHint: "Waiting to be let in…",
  knockCallNotActive: "No one is in this call yet to let you in. Try again when the call is live.",
  muteParticipant: "Mute participant",
  unmuteParticipant: "Unmute participant",
  mutedByHost: "A host muted your microphone",
  unmutedByHost: "A host unmuted your microphone",
  microphoneMuted: "Microphone muted",
  microphoneUnmuted: "Microphone unmuted",
  mutedParticipant: (name: string) => `Muted ${name}`,
  unmutedParticipant: (name: string) => `Unmuted ${name}`,
  pipNotReady: "Camera preview is not ready yet.",
  pipUnsupported: "Picture-in-Picture is not supported in this browser.",
  pipError: "Could not open Picture-in-Picture.",
  openPip: "Open picture-in-picture",
  openSystemPip: "Open system Picture-in-Picture",
  youLabel: "You",
  selfPreview: (name: string) => `${name} (you)`,
  participantJoined: (name: string) => `${name} joined the call`,
  participantLeft: (name: string) => `${name} left the call`,
  callEndedBy: (name: string) => `Call ended by ${name}.`,
  youWereLetIn: "You were let in.",
  joinDenied: "The host denied your request to join.",
  couldNotSendMessage: "Could not send message.",
  callActiveInAnotherTab: "A call is already active in another tab.",
  miniPlayerLabel: "Ongoing call",
  /** Generic product title in the mini-player (room codes are opaque ids). */
  miniPlayerTitle: "Meet",
  miniPlayerWaiting: "Waiting to be let in",
  returnToCall: "Return to call",
  hangUp: "Hang up",
  sidebarChannels: "My channels",
  sidebarSharedWithMe: "Shared with me",
  sidebarDirectMessages: "Direct messages",
  sidebarMeetings: "Today’s meetings",
  upcomingStartsInOneMinute: "starts in 1 minute",
  upcomingStartsInMinutes: (minutes: number) => `starts in ${minutes} minutes`,
  upcomingStartsTodayAt: (time: string) => `starts today at ${time}`,
  upcomingStartsTomorrowAt: (time: string) => `starts tomorrow at ${time}`,
  upcomingStartsOnAt: (when: string, time: string) => `starts ${when} at ${time}`,
  liveCall: "In a call",
  dmComposer: (name: string) => `Message ${name}`,
  chatActionFailed: "Could not update the conversation.",
  couldNotStartCall: "Could not start the call.",
  couldNotMuteParticipant: "Could not mute that participant.",
  couldNotUnmuteParticipant: "Could not unmute that participant.",
  newChannel: "New channel",
  newMeeting: "New meeting",
  scheduleMeeting: "Schedule",
  newChannelMenu: "New",
  editChannel: "Edit channel",
  editMeeting: "Edit meeting",
  channelNameLabel: "Name",
  channelKindLabel: "Type",
  channelKindChannel: "Channel",
  channelKindMeeting: "Meeting room",
  channelScopeLabel: "Owner",
  channelScopePersonal: (ownerLabel: string) => ownerLabel,
  channelScopeGroup: (name: string) => name,
  channelScopeReadOnlyLabel: "Owner",
  changeChannelOwnerConfirmTitle: "Change owner?",
  changeChannelOwnerConfirmToGroup: (groupName: string) =>
    `Move this collection to ${groupName}? People in that group will see it.`,
  changeChannelOwnerConfirmToPersonal: "Move this collection back to your personal space?",
  changeChannelOwnerConfirm: "Change owner",
  createChannelButton: "Create",
  saveChannelButton: "Save",
  cancel: "Cancel",
  deleteChannel: "Delete channel",
  deleteMeeting: "Delete meeting",
  deleteChannelConfirmTitle: "Delete channel?",
  deleteMeetingConfirmTitle: "Delete meeting?",
  deleteChannelConfirmDescription:
    "Messages in this channel will be permanently deleted. This cannot be undone.",
  deleteMeetingConfirmDescription:
    "This meeting and its conversation will be permanently deleted. This cannot be undone.",
  delete: "Delete",
  shareChannelSectionTitle: "People with access",
  shareChannelSectionHint:
    "Share this channel with workspace people or groups. Email guests cannot be added.",
  shareChannelAddPlaceholder: "Add people or groups",
  shareChannelSearchEmpty: "No matching people or groups.",
  shareChannelOffline: "Sharing needs a connection.",
  removeChannelShareTitle: "Remove access?",
  removeChannelShareConfirm: "Remove",
  guestLinkHint: "Anyone with this link can join as a guest.",
  guestLinkAfterCreate: "A guest link will be ready after you create this meeting room.",
  emptyChannelMain: "Select a channel to start chatting.",
  chatColumnPlaceholder: "Chat will appear here.",
  membersCount: (count: number) => `${count} members`,
  threadPeopleCount: (count: number) =>
    count === 1 ? "1 person in thread" : `${count} people in thread`,
  startCall: "Start call",
  joinCall: "Join call",
  start: "Start",
  meet: "Meet",
  startAudioOnly: "Meet (Audio Only)",
  startCallMenu: "More call options",
  join: "Join",
  joined: "Joined",
  leave: "Leave",
  leaveCallStub: "Stop preview call",
  mute: "Mute",
  unmute: "Unmute",
  stopVideo: "Stop video",
  startVideo: "Start video",
  enableAudio: "Enable audio",
  disableAudio: "Disable audio",
  enableVideo: "Enable video",
  disableVideo: "Disable video",
  meetingStarted: "Meeting started",
  inCallCount: (count: number) => `${count} in call`,
  expandCall: "Expand call",
  collapseCall: "Collapse call",
  restoreCall: "Show chat",
  resizeCall: "Resize call stage",
  meetInChannel: (name: string) => `Meet in ${name}`,
  chatInChannel: (name: string) => `Chat — ${name}`,
  speaking: "Speaking",
  camerasOffAudioOnly: "Cameras off — audio only",
  startingCamera: "Starting camera...",
  typingOne: (name: string) => `${name} is typing…`,
  typingTwo: (first: string, second: string) => `${first} and ${second} are typing…`,
  typingMany: (count: number) => `${count} people are typing…`,
  threadTitle: "Thread",
  threadClose: "Close thread",
  threadBack: "Back to chat",
  participantsShort: (count: number) => `${count} in call`,
} as const;
