export const meetLabels = {
  callEndedTitle: "Call ended",
  missingInviteTitle: "Nothing here",
  missingInviteBody: "This meeting is not active. Ask the host for a fresh invite link.",
  checkingInviteTitle: "Checking meeting",
  checkingInviteBody: "Validating this invite link...",
  lobbyJoinTitle: "Ready to join?",
  lobbyHostTitle: "Ready when you are.",
  displayNameLabel: "Display name",
  cameraLabel: "Camera",
  microphoneLabel: "Microphone",
  speakerLabel: "Speaker",
  joinMeeting: "Join meeting",
  askToJoin: "Ask to join",
  startMeeting: "Start meeting",
  inviteRequired: "Invite link required",
  cancelRequest: "Cancel request",
  knocking: "Knocking",
  knockingHint: "Waiting for the host to let you in",
  leaveCall: "Leave call",
  endCall: "End call",
  leaveCallTitle: "Leave this call?",
  endCallTitle: "End call for everyone?",
  leaveCallDescription: "This only disconnects you from the meeting.",
  endCallDescription: "This will disconnect all participants from the meeting.",
  shareLinkHint: "Anyone with this link can join the room.",
  shareLinkPlaceholder: "Start a meeting to generate a share link",
  shareLinkWaiting: "Share link will appear here.",
  copyLink: "Copy link",
  linkCopied: "Link copied",
  chatTitle: "Chat",
  chatEmpty: "Messages from participants will appear here.",
  chatPlaceholder: "Send a message",
  sendMessage: "Send",
  waitingForOthers: "Waiting for others to join...",
  presenting: "Presenting",
  sharingScreen: "You're sharing your screen",
  participantsTooltip: (count: number) => `${count} of 4 participants`,
  toggleChatShow: "Show chat",
  toggleChatHide: "Hide chat",
  shareScreen: "Share screen",
  stopSharing: "Stop sharing",
  devices: "Devices",
  shareLink: "Share link",
  signOut: "Sign out",
  someoneKnocking: "Someone is knocking to join.",
  wantsToJoin: "wants to join",
  waitingToJoin: (count: number) => `${count} waiting to join`,
  muteParticipant: "Mute participant",
  muteSoon: (name: string) => `Mute controls for ${name} will be added soon`,
  pipNotReady: "Camera preview is not ready yet.",
  pipUnsupported: "Picture-in-Picture is not supported in this browser.",
  pipError: "Could not open Picture-in-Picture.",
  openPip: "Open picture-in-picture",
  openSystemPip: "Open system Picture-in-Picture",
  youLabel: "You",
  selfPreview: (name: string) => `${name} (you)`,
} as const;
