import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { readFileSync, writeFileSync } from "node:fs";
import { buildOpenApiBuiltJson } from "./build-openapi-built-json.mjs";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDir, "..");
const generatedDir = path.resolve(packageRoot, "openapi/generated");
const builtDocPath = path.resolve(generatedDir, "openapi.built.json");
const openApiTypesPath = path.resolve(generatedDir, "openapi-types.ts");
const mailTypesPath = path.resolve(generatedDir, "mail-types.ts");

function buildMailTypesModule() {
  const builtDoc = JSON.parse(readFileSync(builtDocPath, "utf8"));
  const schemaObj = builtDoc?.components?.schemas ?? {};
  const schemaNames = Object.keys(schemaObj)
    .filter((name) => name.startsWith("Mail") || name === "OkResponse")
    .sort((a, b) => a.localeCompare(b));

  const aliasLines = schemaNames.map(
    (name) => `export type ${name} = components["schemas"]["${name}"];`,
  );

  const fileContents = [
    "// Auto-generated by scripts/typegen-mail.mjs. Do not edit manually.",
    "",
    'import type { components, paths } from "./openapi-types";',
    "",
    "export type MailSchemas = components[\"schemas\"];",
    "export type MailPaths = {",
    "  [K in keyof paths as K extends `/mail/${string}` ? K : never]: paths[K];",
    "};",
    "",
    ...aliasLines,
    "",
    "export type { components, paths };",
    "",
  ].join("\n");

  writeFileSync(mailTypesPath, fileContents, "utf8");
}

/**
 * Generate runtime OpenAPI JSON and TypeScript types for mail.
 */
export async function generateMailTypes() {
  buildOpenApiBuiltJson();

  execFileSync("pnpm", ["exec", "openapi-typescript", builtDocPath, "-o", openApiTypesPath], {
    cwd: packageRoot,
    stdio: "inherit",
  });

  buildMailTypesModule();
}

if (import.meta.url === new URL(process.argv[1], "file://").href) {
  await generateMailTypes();
  process.stdout.write(`Wrote ${builtDocPath}\n`);
  process.stdout.write(`Wrote ${openApiTypesPath}\n`);
  process.stdout.write(`Wrote ${mailTypesPath}\n`);
}
