import type { DriveFile } from "@/drive-core/src/drive-models";

export const DRIVE_MOCK_FILES: DriveFile[] = [
  {
    id: "f-studio",
    notebook: "Folder",
    category: "Folder",
    date: "Mon",
    title: "Studio Assets",
    excerpt: "12 items · 84 MB",
    body: ["Brand guidelines, logos and templates."],
    tags: [],
    wordCount: 0,
    parent: "My Drive",
    kind: "folder",
    size: "84 MB",
  },
  {
    id: "f-archives",
    notebook: "Folder",
    category: "Folder",
    date: "12 Sep",
    title: "Archives",
    excerpt: "8 items · 22 MB",
    body: ["Older work, kept for reference."],
    tags: [],
    wordCount: 0,
    parent: "My Drive",
    kind: "folder",
    size: "22 MB",
  },
  {
    id: "f1",
    notebook: "Doc · 240 KB",
    category: "Document",
    date: "10:42",
    title: "Autumn Issue — Final Proofs.pdf",
    excerpt: "Last edited by Hana Ito · shared with 3 people",
    body: ["A bound PDF of the autumn issue, ready for sign-off."],
    tags: ["editorial"],
    wordCount: 0,
    parent: "My Drive",
    kind: "doc",
    size: "240 KB",
  },
  {
    id: "f2",
    notebook: "Image · 4.2 MB",
    category: "Image",
    date: "Yesterday",
    title: "Cover-Photo-Granite.jpg",
    excerpt: "Hero image for the Nordic Coast feature",
    body: ["Shot on a Mamiya 7, scanned at 4000 dpi."],
    tags: ["photo"],
    wordCount: 0,
    parent: "My Drive",
    kind: "image",
    size: "4.2 MB",
  },
  {
    id: "f6",
    notebook: "Audio · 8 MB",
    category: "Audio",
    date: "Sat",
    title: "interview-ada-pereira.m4a",
    excerpt: "Recorded for the Northlight feature",
    body: [],
    tags: [],
    wordCount: 0,
    parent: "My Drive",
    kind: "audio",
    size: "8 MB",
  },
  {
    id: "f-logo",
    notebook: "Image · 1.1 MB",
    category: "Image",
    date: "Mon",
    title: "studio-mark-final.svg",
    excerpt: "Vector mark, final lockup",
    body: [],
    tags: [],
    wordCount: 0,
    parent: "My Drive/Studio Assets",
    kind: "image",
    size: "1.1 MB",
  },
  {
    id: "f-guide",
    notebook: "Doc · 3.4 MB",
    category: "Document",
    date: "Mon",
    title: "Brand-Guidelines.pdf",
    excerpt: "Typography, color, voice",
    body: [],
    tags: [],
    wordCount: 0,
    parent: "My Drive/Studio Assets",
    kind: "doc",
    size: "3.4 MB",
  },
  {
    id: "f4",
    notebook: "Video · 128 MB",
    category: "Video",
    date: "30 Sep",
    title: "Bindery-Walkthrough.mov",
    excerpt: "Short film from the Kyoto bindery visit",
    body: ["A 3-minute clip walking through the bindery floor."],
    tags: ["travel"],
    wordCount: 0,
    parent: "Shared with me",
    kind: "video",
    size: "128 MB",
  },
  {
    id: "f5",
    notebook: "Archive · 12 MB",
    category: "Archive",
    date: "24 Sep",
    title: "old-website-export.zip",
    excerpt: "Archive of the previous studio site",
    body: [],
    tags: [],
    wordCount: 0,
    parent: "My Drive/Archives",
    kind: "archive",
    size: "12 MB",
  },
];
