export const driveLabels = {
  sidebarMyDrive: "My Drive",
  sidebarRecent: "Recent",
  sidebarStarred: "Starred",
  sidebarTrash: "Trash",
  sidebarSharedDrives: "Shared drives",
  searchPlaceholder: "Search in Drive...",
  emptyFolder: "This folder is empty",
  folderListingLoading: "Loading folder…",
  dropUploadHint: "Drop files to upload to",
  newButton: "New",
  newFolder: "New folder",
  uploadFiles: "Upload files",
  newDocument: "New document",
  newSpreadsheet: "New spreadsheet",
  newPresentation: "New presentation",
  gridView: "Grid view",
  listView: "List view",
  selectionDone: "Done",
  selectionStar: "Star",
  selectionMove: "Move",
  selectionDownload: "Download",
  selectionMoveToTrash: "Move to trash",
  selectionDeletePermanently: "Delete permanently",
  detailDownload: "Download",
  detailStar: "Star",
  detailUnstar: "Unstar",
  detailRename: "Rename",
  detailMove: "Move",
  detailDelete: "Delete",
  folderPickerDrivesRoot: "Drives",
  moveDialogTitle: "Move to folder",
  moveDialogDescription:
    "Browse folders like in Drive. Click to select a destination, double-click to open a folder.",
  moveDialogSearchPlaceholder: "Search folders…",
  moveDialogEmpty: "No folders match your search.",
  moveDialogCancel: "Cancel",
  moveDialogConfirm: "Move here",
} as const;

export type DriveUILabels = typeof driveLabels;
