export const driveLabels = {
  sidebarMyDrive: "My Drive",
  sidebarRecent: "Recent",
  sidebarStarred: "Starred",
  sidebarTrash: "Trash",
  sidebarGroups: "Groups",
  searchPlaceholder: "Search in Drive...",
  emptyFolder: "This folder is empty",
  dropUploadHint: "Drop files to upload to",
  newButton: "New",
  newFolder: "New folder",
  uploadFiles: "Upload files",
  newDocument: "New document",
  newSpreadsheet: "New spreadsheet",
  newPresentation: "New presentation",
  gridView: "Grid view",
  listView: "List view",
  selectionDone: "Done",
  selectionStar: "Star",
  selectionDownload: "Download",
  selectionMoveToTrash: "Move to trash",
  selectionDeletePermanently: "Delete permanently",
  detailDownload: "Download",
  detailShare: "Share",
  detailStar: "Star",
  detailUnstar: "Unstar",
  detailDelete: "Delete",
} as const;

export type DriveUILabels = typeof driveLabels;
