/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebdavRouteImport } from './routes/webdav'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as MailRouteImport } from './routes/mail'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as IndexRouteImport } from './routes/index'

const WebdavRoute = WebdavRouteImport.update({
  id: '/webdav',
  path: '/webdav',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/mail': typeof MailRoute
  '/updates': typeof UpdatesRoute
  '/voice': typeof VoiceRoute
  '/webdav': typeof WebdavRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/mail': typeof MailRoute
  '/updates': typeof UpdatesRoute
  '/voice': typeof VoiceRoute
  '/webdav': typeof WebdavRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/mail': typeof MailRoute
  '/updates': typeof UpdatesRoute
  '/voice': typeof VoiceRoute
  '/webdav': typeof WebdavRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apps' | '/mail' | '/updates' | '/voice' | '/webdav'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apps' | '/mail' | '/updates' | '/voice' | '/webdav'
  id: '__root__' | '/' | '/apps' | '/mail' | '/updates' | '/voice' | '/webdav'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRoute
  MailRoute: typeof MailRoute
  UpdatesRoute: typeof UpdatesRoute
  VoiceRoute: typeof VoiceRoute
  WebdavRoute: typeof WebdavRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webdav': {
      id: '/webdav'
      path: '/webdav'
      fullPath: '/webdav'
      preLoaderRoute: typeof WebdavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRoute,
  MailRoute: MailRoute,
  UpdatesRoute: UpdatesRoute,
  VoiceRoute: VoiceRoute,
  WebdavRoute: WebdavRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
