<?php

declare(strict_types=1);

namespace App\Services\Installer;

use App\LocalConfigFile;
use App\Support\AppPaths;

final class InstallerConfigWriter
{
    public function __construct(private AppPaths $paths)
    {
    }

    /**
     * @param array{pdo: array<string, mixed>, data_dir?: string} $config
     */
    public function writeBootstrap(array $config): void
    {
        if (! isset($config['pdo']) || ! is_array($config['pdo'])) {
            throw new \RuntimeException('Bootstrap config must contain a pdo array.');
        }

        $dataDir = isset($config['data_dir']) && is_string($config['data_dir']) && trim($config['data_dir']) !== ''
            ? trim($config['data_dir'])
            : './wgw-content';
        $pdo = $config['pdo'];
        $target = $this->paths->installRoot().'/wgw-config.php';

        $written = [
            'data_dir' => $dataDir,
            'update_feed_url' => 'https://github.com/woutervroege/wegotworkspace/releases/latest/download/manifest.json',
            'pdo' => $this->normalizePdo($pdo),
        ];

        $php = <<<'PHP'
<?php

declare(strict_types=1);

/**
 * Local bootstrap config generated by the installer.
 *
 * Everything else lives in the app_settings table.
 */

return 

PHP;
        $php .= var_export($written, true).";\n";

        if (file_put_contents($target, $php, LOCK_EX) === false) {
            throw new \RuntimeException('Could not write wgw-config.php');
        }
        @chmod($target, 0600);
        LocalConfigFile::clearCacheForPath($target);
    }

    /**
     * @param array<string, mixed> $pdo
     *
     * @return array<string, mixed>
     */
    private function normalizePdo(array $pdo): array
    {
        if (isset($pdo['sqlite_file']) && is_string($pdo['sqlite_file']) && trim($pdo['sqlite_file']) !== '') {
            return ['sqlite_file' => trim($pdo['sqlite_file'])];
        }

        if (isset($pdo['dsn']) && is_string($pdo['dsn']) && str_starts_with(trim($pdo['dsn']), 'sqlite:')) {
            return ['sqlite_file' => substr(trim($pdo['dsn']), 7)];
        }

        if (isset($pdo['dsn']) && is_string($pdo['dsn']) && trim($pdo['dsn']) !== '') {
            return [
                'dsn' => trim($pdo['dsn']),
                'user' => isset($pdo['user']) && is_string($pdo['user']) ? $pdo['user'] : '',
                'password' => isset($pdo['password']) && is_string($pdo['password']) ? $pdo['password'] : '',
            ];
        }

        throw new \RuntimeException('Bootstrap pdo config must include sqlite_file or dsn.');
    }
}
