<?php

declare(strict_types=1);

namespace App\Services\Installer;

use App\Support\AppPaths;

final class InstallerConfigWriter
{
    public function __construct(private AppPaths $paths)
    {
    }

    /**
     * @param array{pdo: array<string, mixed>, data_dir?: string} $config
     */
    public function writeBootstrap(array $config): void
    {
        if (! isset($config['pdo']) || ! is_array($config['pdo'])) {
            throw new \RuntimeException('Bootstrap config must contain a pdo array.');
        }

        $dataDir = isset($config['data_dir']) && is_string($config['data_dir']) && trim($config['data_dir']) !== ''
            ? trim($config['data_dir'])
            : './wgw-content';
        $pdo = $config['pdo'];
        $target = $this->paths->installRoot().'/wgw-config.php';

        $php = <<<'PHP'
<?php

declare(strict_types=1);

/**
 * Local bootstrap config (WordPress-style constants).
 *
 * Generated by installer. Everything else lives in the app_settings table.
 */

PHP;

        $php .= "\n";
        $php .= "defined('WGW_DATA_DIR') || define('WGW_DATA_DIR', ".var_export($dataDir, true).");\n\n";
        $php .= "defined('WGW_UPDATE_FEED_URL') || define('WGW_UPDATE_FEED_URL', 'https://github.com/woutervroege/wegotworkspace/releases/latest/download/manifest.json');\n\n";

        if (isset($pdo['sqlite_file']) && is_string($pdo['sqlite_file']) && trim($pdo['sqlite_file']) !== '') {
            $php .= "defined('WGW_DB_SQLITE_FILE') || define('WGW_DB_SQLITE_FILE', ".var_export(trim($pdo['sqlite_file']), true).");\n";
        } elseif (isset($pdo['dsn']) && is_string($pdo['dsn']) && str_starts_with(trim($pdo['dsn']), 'sqlite:')) {
            $sqliteFile = substr(trim($pdo['dsn']), 7);
            $php .= "defined('WGW_DB_SQLITE_FILE') || define('WGW_DB_SQLITE_FILE', ".var_export($sqliteFile, true).");\n";
        } elseif (isset($pdo['dsn']) && is_string($pdo['dsn']) && trim($pdo['dsn']) !== '') {
            $user = isset($pdo['user']) && is_string($pdo['user']) ? $pdo['user'] : '';
            $password = isset($pdo['password']) && is_string($pdo['password']) ? $pdo['password'] : '';
            $php .= "defined('WGW_DB_DSN') || define('WGW_DB_DSN', ".var_export(trim($pdo['dsn']), true).");\n";
            $php .= "defined('WGW_DB_USER') || define('WGW_DB_USER', ".var_export($user, true).");\n";
            $php .= "defined('WGW_DB_PASSWORD') || define('WGW_DB_PASSWORD', ".var_export($password, true).");\n";
        }

        if (file_put_contents($target, $php, LOCK_EX) === false) {
            throw new \RuntimeException('Could not write wgw-config.php');
        }
        @chmod($target, 0600);
    }
}
