/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MeetRouteImport } from './routes/meet'
import { Route as MailRouteImport } from './routes/mail'
import { Route as InstallRouteImport } from './routes/install'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetGuestRouteImport } from './routes/meet_.guest'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetRoute = MeetRouteImport.update({
  id: '/meet',
  path: '/meet',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetGuestRoute = MeetGuestRouteImport.update({
  id: '/meet_/guest',
  path: '/meet/guest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/drive': typeof DriveRoute
  '/install': typeof InstallRoute
  '/mail': typeof MailRoute
  '/meet': typeof MeetRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/meet/guest': typeof MeetGuestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/drive': typeof DriveRoute
  '/install': typeof InstallRoute
  '/mail': typeof MailRoute
  '/meet': typeof MeetRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/meet/guest': typeof MeetGuestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/drive': typeof DriveRoute
  '/install': typeof InstallRoute
  '/mail': typeof MailRoute
  '/meet': typeof MeetRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/meet_/guest': typeof MeetGuestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/drive'
    | '/install'
    | '/mail'
    | '/meet'
    | '/notes'
    | '/settings'
    | '/meet/guest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/drive'
    | '/install'
    | '/mail'
    | '/meet'
    | '/notes'
    | '/settings'
    | '/meet/guest'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/drive'
    | '/install'
    | '/mail'
    | '/meet'
    | '/notes'
    | '/settings'
    | '/meet_/guest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DriveRoute: typeof DriveRoute
  InstallRoute: typeof InstallRoute
  MailRoute: typeof MailRoute
  MeetRoute: typeof MeetRoute
  NotesRoute: typeof NotesRoute
  SettingsRoute: typeof SettingsRoute
  MeetGuestRoute: typeof MeetGuestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet': {
      id: '/meet'
      path: '/meet'
      fullPath: '/meet'
      preLoaderRoute: typeof MeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet_/guest': {
      id: '/meet_/guest'
      path: '/meet/guest'
      fullPath: '/meet/guest'
      preLoaderRoute: typeof MeetGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DriveRoute: DriveRoute,
  InstallRoute: InstallRoute,
  MailRoute: MailRoute,
  MeetRoute: MeetRoute,
  NotesRoute: NotesRoute,
  SettingsRoute: SettingsRoute,
  MeetGuestRoute: MeetGuestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
