#!/usr/bin/env bash
# Configure Storybook Live API: .env.local + optional local admin password for dev.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_LOCAL="$ROOT/.env.local"
DB="$ROOT/apps/wegotworkspace/wgw-content/db.sqlite"
USERNAME="${STORYBOOK_DEV_USERNAME:-admin}"
PASSWORD="${STORYBOOK_DEV_PASSWORD:-storybook-dev}"
PROXY_TARGET="${WGW_PROXY_TARGET:-http://127.0.0.1:9080}"
SET_PASSWORD=0

for arg in "$@"; do
  case "$arg" in
    --set-password) SET_PASSWORD=1 ;;
    --no-set-password) SET_PASSWORD=0 ;;
    -h|--help)
      echo "Usage: $0 [--set-password|--no-set-password]"
      echo "  Writes repo-root .env.local for Storybook Live API stories."
      echo "  --set-password  Update admin digest in wgw sqlite (default: on when db exists)"
      exit 0
      ;;
    *)
      echo "Unknown option: $arg" >&2
      exit 1
      ;;
  esac
done

if [[ ! -f "$DB" ]]; then
  echo "WGW database not found at $DB — run the installer first (pnpm docker:up + install)." >&2
  exit 1
fi

if [[ "$SET_PASSWORD" -eq 0 ]]; then
  SET_PASSWORD=1
fi

cat >"$ENV_LOCAL" <<EOF
# Storybook / Vite Live API (generated by tools/setup-storybook-live-api.sh)
# Laravel secrets stay in packages/api/.env — see docs/env.md

VITE_WGW_USE_LIVE_API=1
VITE_WGW_API_BASE_URL=/api/v1
VITE_WGW_DEV_USERNAME=${USERNAME}
VITE_WGW_DEV_PASSWORD=${PASSWORD}

WGW_PROXY_TARGET=${PROXY_TARGET}
EOF

echo "Wrote $ENV_LOCAL"

if [[ "$SET_PASSWORD" -eq 1 ]]; then
  UPDATED="$(
    USERNAME="$USERNAME" PASSWORD="$PASSWORD" DB="$DB" php <<'PHP'
<?php
declare(strict_types=1);
$username = getenv('USERNAME') ?: '';
$password = getenv('PASSWORD') ?: '';
$db = getenv('DB') ?: '';
if ($username === '' || $password === '' || $db === '' || ! is_file($db)) {
    fwrite(STDERR, "Missing username, password, or database.\n");
    exit(2);
}
$hash = password_hash($password, PASSWORD_DEFAULT);
if ($hash === false) {
    fwrite(STDERR, "Password hashing failed.\n");
    exit(2);
}
$pdo = new PDO('sqlite:'.$db);
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$stmt = $pdo->prepare('UPDATE users SET digest = ? WHERE username = ?');
$stmt->execute([$hash, $username]);
echo (string) $stmt->rowCount();
PHP
  )"
  if [[ "$UPDATED" != "1" ]]; then
    echo "No user '${USERNAME}' in database — create the install account first." >&2
    exit 1
  fi
  echo "Set password for '${USERNAME}' (local dev / Storybook only)."
fi

if curl -sf -o /dev/null -w "" "${PROXY_TARGET}/api/v1/health" 2>/dev/null; then
  CODE="$(curl -s -o /dev/null -w "%{http_code}" -X POST "${PROXY_TARGET}/api/v1/auth/token" \
    -H 'Content-Type: application/json' \
    -d "{\"username\":\"${USERNAME}\",\"password\":\"${PASSWORD}\"}")"
  if [[ "$CODE" == "200" ]]; then
    echo "Auth check OK (${PROXY_TARGET}/api/v1/auth/token)."
  else
    echo "Warning: auth/token returned HTTP ${CODE} — verify API is running and credentials." >&2
  fi
else
  echo "API not reachable at ${PROXY_TARGET} — start with pnpm docker:up or pnpm dev:api, then restart Storybook."
fi

echo ""
echo "Open Storybook Live API:"
echo "  http://127.0.0.1:6006/?path=/story/apps-wegotworkspace--live-api"
echo "  http://127.0.0.1:6006/?path=/story/apps-wegotworkspace--live-docs"
